---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: dns
spec:
  encryptedData:
    api-token: AgCXV9crH7HIcVDJs6wMjKCQzdMOD3oUoJQxgrFfIuglxx7M+EMirScEC9m94jqoz7qts+bhWKhUp8LQFGQizT35MtPworL0+Vzz9b7/A4HNzRZ2FzDoKPRNDn23VugvJk48/9027QTD55OnavCrhKIrnzLehLmZT5gq2i1t2fmKJtDUxv6OKeehGwpPQK+BBB1uRIH3gZaby0aMqBWFb0/UsT32DDJesHwRrwA7AwEo34cpxPBBsNIjwEdAqFLjsPw3VsN/skbKrFR+8z+76da9fUwddBG23ekdLDVMMKWrTN2wUwxtfafYUsiLs/Q5xr4Rx9LnP1PuaXx1plRCNNwDz2rbWxHAoDp9euV4ppjGWdVYnGV0fAv/X60vsUF8FIj3SoR5P3dxV+tR0mpiCclpHMKPkzjh+++xgGCyrDKxdftmFQjlJW5Ql/X/WJi+oobJRf+4PH6b2fgF/0PAII3yqNH7N8nrmZnVnB5i8jdsiNJBVXaZ6TJ90h3UQPWgLQs9jjRYw6rIP6aGxDYXstcc8TIwO+W6QKrX1juVHApM1ZVwDmkYANXg+ti2C/aX6DHDjqoGqxgnLwkJ6ehD4cazbN1QpgGxI6T/UdYCrTujMmGDRKFrV5hJcQ8NQfefKx1QsNiEwNzlo6RXTzE86ytusiPVHIR5PK7K8gV0o+TYe3TqGsBLTX+v8SQeK6XEdp45Vq/e9DdhqM9ChJX9KweobCbcjUB3bQEBn6V2+gttyWOMoOcXsLIA
  template:
    metadata:
      name: cloudflare-api-token
      namespace: dns
