apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-media
  resources:
    requests:
      storage: 10Ti
