apiVersion: apps/v1
kind: Deployment
metadata:
  name: qui
  namespace: media
  labels:
    app: qui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qui
  template:
    metadata:
      labels:
        app: qui
    spec:
      containers:
        - name: qui
          image: ghcr.io/getqui/qui:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qui-config
