apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qui-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-fast
  resources:
    requests:
      storage: 1Gi
