---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAhDnLZNa5EMZpKQnmGnHkDZy1sg9P23Ht+c9JmSsf1JULAor190WJGKceHP4ok8I2ymRcfJEz4V1dNCaWkBDhnHKwcpl0wgB2lvdkdW0a4Y2MTWjfqB3+LRtiNVqMQiCTx14tTyA6WbfdSaROcVsR7uG7Oxk6kNB2UpeTKeU6iEEHpIwBfh3FbEXZKBRAEYFtU9mcv0sGI/ZID6G+UPVcBU3lqXCnihIZPDzL4e24jctYqmfeb5WLQOA8bibs7PqOSuwwh2lfhnwQeDIl5ZrZpVO4PNQoLmmEez9BfTR2buaakrRR0algAgKv/zHcOSXZWTCecXOu64O/6yE9/srhVfjrmY6UCWb9CmWhA35tGd2DNipLX0Lwck01a5f2klw1cIz/StGSTeDGQfmh4kyeWRcNRjMFWRPwkjPy41P1j85O/v5oa33A+5PYEvhsNhBFqCjG1dd44MoPefr45McI4rsWGGnAKR86Vy+IfL0PMzmXcOsr5Ut5ApePCmjbNxmAhGoG/mDkAbofSN6hVvU99M1/iElRHhoGKRpKpRHL+8cLHJgJ6zXZICCKwszA+/0r14TmSHbjXKRD//glG/dSWA+M7Sx+ACUBRkSht5k6wJH2u3CrRdKu1zQO89bk1EZqHUAD5KEt9ihjxEneTUno3F9HtH40PhTRiKIJjPmd/5fcIzUfHq3el+hdJXlt5TGsKrESeoX1QSTE7pMY/
    admin-user: AgBrON5xV3OZ30tI2Fxmce9gwM6sZQww7QbIGqvPCueIClfkQkVMLnnJ+APiDKc1DntIVOEm8KsFSfjKx9ovMs0ohbLV0QVJrH3TSxhqn1BMuuUkrnU08XeRaVzDPDrvljCPcKMi2qUqzGxZJnycxPMxzMi7eu9C2xZoTldduWXxWDJZc9+DwMR3nlDr7aR2OX8XfS/b7HqLJhYfHRmGId56uU7oem0N/n9BiriuGyl/AEiC8DdzRe1NSsRtsiJ4NQSF7iJagyJRAykE9tk2iwmPLJquGAw4qulDKusv8XR3wM9Kw1l8rfXTpCnJL906QhnNEfBRx3DEu7S8fCqC+SQNp/WGeFYGr24a3B78KX7ies6T5135FJDfAfm7O4UpPNV+6Czee0yO5gd5IoBejTwdk4qpU5sizWeqopceIEZR7rr4Lx9U9KvSOPv4bBn+zq6GocTgvDV/+i7lxCpHvki9r8wDCA7QYkgOWVe1GLLsEtd3RGfI8GjDyMPnDrhbTPd3GLStftz3KNSZD6NnvC7YOzzpW6gKsC/RRFxRosUa+J3IoKHHG22N9WO7WdZFwg0Vci1/mCvmtAWiCAZRRMbY+LruAnKbEDZDN9RrjelXVfcLYgph2nkHBRqH86I6lv7T2HSqdjJGc/EpH3Boi+qp+cT2j2puVA1Cns7gJhu0lQXGypIWVTiD0siJv8kek2OCNBI9zA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
