apiVersion: batch/v1
kind: Job
metadata:
  name: cilium-install
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: cilium-install
          image: quay.io/cilium/cilium-cli:v0.16.2
          imagePullPolicy: IfNotPresent
          args:
            - install
            - "--wait=false"
            - "--version=v1.16.3"
            - "--namespace=kube-system"
            - "--values=-"
          stdin: true
      securityContext:
        runAsUser: 0
      serviceAccountName: default
