apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-fast
  volumeName: pv-radarr
  resources:
    requests:
      storage: 5Gi
