---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBMdUBnvg3gs57hi/pkf2yRrs0BZhvill+hoS+hXL14dIAQhpyquE2T0kXTi4ueJFFoSMUu+Xx76uzz5VusrEnN6Pd7KbIEyfSE/vrkW4wQ0kVfrsAHzQjc0EwW6x6m1N1XubHtsVnfxEEj0y53PDwZoXtODxxY4C0bpn5LMV5DqWPTAKkJDQulrLrsR3G882WAWYY5QHeDvHbMmBtE3wFuKyPY3/R22A6FZqlM7AGXMQ67gUuAuvwL+r8nyKbRLM0aKD/a1kAHehxOLL8t33ifzyebiE1u0NxOpMB799BjXGC0cGiaMdNdioQjbNcHZeM3FXUNlBBitwU9Kt6fTKRRXt3oEVz48UUegwDLHFnVKhcY3AmHTyg4+xTmOHRIdPWPJg4CwXNyacT1FDgE+ZmNDwrPSe9bHe0hFJRwsXwTi4CpnKwLet/4hhu7tbPrBQRsIFNzkuKCDoN2VNS38wiTj/pQkn9pDz3wT+SxS/St0YOPE46WlZBzfzUc+L+8swZn+ZpcToS34qELTOwQ6VfGRKS3DaP+zZaj7aymulOYptjZV3EkLpctOlcIOGvZwIAXhTxsiH4uMzQolfbIQQs7sNbGONYwtDp5sb3dGWyvVJ8MSLSEvgOCMcTgrQfuMryJus2N1o5Ma/V/2/lXm64Ya+Vgu02Oxrg2viEd2En1xMp25XtWsKaFSMsm0dRgbvB/pUOcpBWlm2I6HCYwEG/C73seK51KJROndIZdGfB8KgFKWXCnUxLW
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
