apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-fast
  volumeName: pv-jellyfin
  resources:
    requests:
      storage: 20Gi
