---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCYIlZclZyNA01m9KUFlJBBn3kI/ZEerBVUhvrEHcySTmZt+FZTCpIXgmj02IYwgmychpeOyJJVytd/tuzSM2KXZhlqSZejpgsJ27HfKZtA2P63CkkC5tAwyw5naJeNxSKrfWnNVymFFLFJIZNSTAnQFNjZcdaN8JN4jsaIHYz0TndDTIzniPIya6kNIHFPnluMZgaTaAQvQkIu9bttyXeC0PgwlxEZydZtK/icigk4uIkBUJTWdJ9OnTJrijIOpsztC58Wi5Ky5hpBG4GXL+4pWOh4YO+rHFzO36vE5a0HzJuav6PZZvx9ebohtFPQ4isgTjy1BlzX9aFzgODeUaCxjy7uTE6dc8zOjlVuoWevcobU6sceR5AWWIYf9uXxkOhtuKMU1mgjWaMRV07dtBEUy5hbo+eFLoHmd3mUro8jYS6m7mNJjqkqXrFga9hz5KMIzhlt11pIvDI72j0fUC9ED6mkT0X8W8WPSU22dFPeyq51HFhrrOFtBCxHkDZgNXL/0Ga7Mg+jytoO17ZylXV/vAgGEmcWhRhXUoBhZA8uBtXEcUqCxj1n3lXnnJw7X2yCKXQ0hc3s0W4ESdlEMGgT/3JBfMr0aW5G3POzjwqnbcSG0MQyLsNbNUvrHwmo3f6QDKHfsRh1P6xBMxVAxxMxX17eGId3WzJwNZ8YmTQ80d+DHos7wVFSxY1Q7ufCv154KgvheU1Z1rYcm3DHKuM7kyD7Iqc3EuIeb2haIKEhiXJ8j8a0QUzJiG/piWcApCq/pvK4wCHxGrpBtpnPTJqc0Ukg0c/C56A/YVX9jb/h9P2QX9uMKzd0Np9K0aINq3DGPcP8S0QSSBdV36aruWU0GvNhC6w17bYPEKWz2NGBdxtJ8A33/oILmeAxoNfGHO+vjrqltj+oGXDPSQbVvxcbJAyENBY4Bk0DNG7jlruHEb5GuogbNyHL3AeAyDgHFH0JJU47
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
